name: Build, test, and lint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Build & Test
    strategy:
      matrix:
        os: ['ubuntu-latest']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Update dependencies
        run: sudo apt-get update
      - name: Install dependencies
        run: sudo apt-get install -y pkg-config libudev-dev openssh-client
      - uses: actions/checkout@v2
      - name: Configure SCCache
        run: |
          mkdir -p $HOME/.local/bin
          curl -L "https://github.com/mozilla/sccache/releases/download/v0.3.0/sccache-v0.3.0-x86_64-unknown-linux-musl.tar.gz" | tar xz
          mv -f sccache-v0.3.0-x86_64-unknown-linux-musl/sccache $HOME/.local/bin/sccache
          chmod a+x $HOME/.local/bin/sccache
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Configure build cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-${{ matrix.os }}-fast-${{ hashFiles('**/Cargo.lock') }}
      - name: Save sccache
        uses: actions/cache@v2
        continue-on-error: false
        with:
          path: /home/runner/.cache/sccache
          key: ${{ runner.os }}-sccache-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
                        ${{ runner.os }}-sccache-
      - name: Start sccache server
        run: sccache --start-server
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
      - name: Start ssh-agent
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: ssh-agent -a $SSH_AUTH_SOCK > /dev/null
      - name: Build & Test
        run: cargo test --profile ci --workspace
        env:
          RUSTFLAGS: -D warnings
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          RUSTC_WRAPPER: sccache
          SCCACHE_CACHE_SIZE: 2G
          SCCACHE_DIR: /home/runner/.cache/sccache
      - name: Print sccache stats
        run: sccache --show-stats
      - name: Stop sccache server
        run: sccache --stop-server || true

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Update dependencies
        run: sudo apt-get update
      - name: Install dependencies
        run: sudo apt-get install -y pkg-config libudev-dev
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: clippy, rustfmt
          toolchain: 1.59.0
      - name: Cache cargo registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: cargo-${{ runner.os }}-fast-${{ hashFiles('**/Cargo.lock') }}
      - name: Run clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all --tests
        env:
          RUSTFLAGS: -D warnings
      - name: Check formating
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - name: Update dependencies
        run: sudo apt-get update
      - name: Install dependencies
        run: sudo apt-get install -y pkg-config libudev-dev
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
      - name: Docs
        run: cargo doc --profile ci --workspace --no-deps
        env:
          RUSTDOCFLAGS: -D warnings
