name: Build, test, and lint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Build & Test
    strategy:
      matrix:
        os: ['ubuntu-latest']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Update dependencies
        run: sudo apt-get update
      - name: Install dependencies
        run: sudo apt-get install -y pkg-config libudev-dev openssh-client cmake
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
      - name: Start ssh-agent
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: ssh-agent -a $SSH_AUTH_SOCK > /dev/null
      - name: Build & Test
        run: cargo test --profile ci --workspace
        env:
          RUSTFLAGS: -D warnings
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Update dependencies
        run: sudo apt-get update
      - name: Install dependencies
        run: sudo apt-get install -y pkg-config libudev-dev
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: clippy, rustfmt
          toolchain: 1.63
      - name: Run clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all --tests
        env:
          RUSTFLAGS: -D warnings
      - name: Check formating
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - name: Update dependencies
        run: sudo apt-get update
      - name: Install dependencies
        run: sudo apt-get install -y pkg-config libudev-dev
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
      - name: Docs
        run: cargo doc --profile ci --workspace --no-deps
        env:
          RUSTDOCFLAGS: -D warnings
